### ISSUE TITLE
Linter does not seem to work anymore with TF 0.11.14

### ISSUE THREAD

**Issue by martinseener** [patrickrgaffney/SublimeLinter-contrib-terraform#4]
Hi,
i've tried your linter yesterday but sadly it doesn't seem to work. By manually trying the command that it normally does, the same error occures.
I found out that validating works just with `cat file.tf | terraform validate`. I'm unsure about the -json thingy but its def. a single dash before json and not two dashes. Can you please check the plugin with Terraform 0.11.14 again?
I'm using Linux Mint 19.3 (Ubuntu 18.04 LTS) currently.
If needed i can also assist you in bug fixing!
Thanks alot.

**Comment by patrickrgaffney** [comment]
Sorry for the extended response time, this must have gotten lost in my Github notifications.

So this plugin requires a minimum version of v0.12.x for Terraform. The `-json` flag was added to the `validate` command [in v0.12.0](https://github.com/hashicorp/terraform/blob/v0.12/CHANGELOG.md#other-improvements) — and that flag is really the reason this plugin exists. Without it the unstructured output isn't easily parsed. That minimum requirement isn't documented anywhere, and that's on me. I will update the README to explicitly state this minimum requirement.

As for the `--json` flag, you can provide either single or double dashes. Terraform uses the [`cli`](https://github.com/mitchellh/cli) package for handling its command-line interface, and it allows for either format.

With [v0.13.x looming on the horizon](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md), I don't really feel it's worth the effort to switch from using the JSON output to try and build a regex to handle the unstructured output. Sorry again for the late response.
